[package]
name = "os"
description = "A simple OS following blog series: https://os.phil-opp.com/."
version = "0.1.0"
edition = "2021"

[dependencies]
bootloader = "0.9.23"
# TODO: upgrade to newer bootloader version
# bootloader = "0.10.13"
